#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
mysterium_toxicology.py
Corrected Specialized Toxicological Extraction Engine.
Maps functional lexical category strings to find true psychoactive overlaps.
"""

import csv
import os

INPUT_FILE = "great_mystery_network_map.csv"
OUTPUT_FILE = "mysterium_toxicology_matrix.csv"

def main():
    print("="*60)
    print("MYSTERIUM TOXICOLOGY & PSYCHOACTIVE FILTER ACTIVE")
    print("="*60)
    
    if not os.path.exists(INPUT_FILE):
        print(f"[!] Error: Cannot locate source network map '{INPUT_FILE}'.")
        return

    # Corrected: Match the exact thematic tags generated by mysterium_engine.py
    toxic_categories = {
        "pharmakeia", "christa", "perichristos", "epichristos", 
        "thanasimos", "strychnos", "antidotos", "ios",
        "christing_active", "christing_middle", "christing_passive"
    }
    
    ecstatic_categories = {
        "manias", "manike", "oistros", "ecstasis", "lyssa", "λύσσα", 
        "mysterion", "orgia", "ὄργια", "telete", "τελετή", "μύωψ",
        "katharsis", "myesis", "aporrheton", "arrhetos", "amyeitos", "myops"
    }

    snippet_groups = {}

    with open(INPUT_FILE, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            work = row.get("Work_Title")
            loc_ref = row.get("Location_Reference")
            theme = row.get("Matched_Themes")
            snippet = row.get("Greek_Context_Snippet")
            url = row.get("Perseus_Web_URL")
            keyword = row.get("Greek_Keywords")
            
            if snippet and theme:
                if snippet not in snippet_groups:
                    snippet_groups[snippet] = {
                        "work": work,
                        "location": loc_ref,
                        "themes": set(),
                        "keywords": set(),
                        "url": url
                    }
                snippet_groups[snippet]["themes"].add(theme.strip())
                snippet_groups[snippet]["keywords"].add(keyword)

    toxicological_rows = []
    
    for snippet, data in snippet_groups.items():
        # Check for matching category strings smoothly using intersecting loops
        has_substance = any(t in toxic_categories for t in data["themes"])
        has_ecstasy = any(t in ecstatic_categories for t in data["themes"])
        
        if has_substance and has_ecstasy:
            toxicological_rows.append([
                data["work"],
                data["location"],
                " | ".join(data["themes"]),
                " | ".join(data["keywords"]),
                snippet,
                data["url"]
            ])

    with open(OUTPUT_FILE, mode='w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(["Work_Title", "Location_Reference", "Overlapping_Themes", "Greek_Keywords", "Greek_Context_Snippet", "Perseus_Web_URL"])
        writer.writerows(toxicological_rows)
        
    print(f"[+] Filtering complete.")
    print(f"[*] Successfully isolated {len(toxicological_rows)} psychoactive/lethal ritual nodes to '{OUTPUT_FILE}'.")
    print("="*60)

if __name__ == "__main__":
    main()
